version: '1'

services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME:-ai_assistant}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_TYPE: ${DB_TYPE}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - pg-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    command: redis-server --port 5370 --save 60 1 --appendonly yes  # автосохранение + AOF
    ports:
      - "5370:5370"
    expose:
      - "5370"
    networks:
      - pg-network
    volumes:
      - ./redis_data:/data
    restart: unless-stopped

  database_init:
    build:
      context: .
      dockerfile: database_init/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      - pg-network
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_TYPE: $DB_TYPE

  database_api:
    build:
      context: .
      dockerfile: database_api/Dockerfile
    depends_on:
      database_init:
        condition: service_completed_successfully
    links:
      - postgres
    ports:
      - "8002:8002"
    networks:
      - pg-network
    env_file:
      - .env
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_TYPE: $DB_TYPE


  voice_to_text_api:
    build:
      context: .
      dockerfile: voice_to_text_api/Dockerfile
    depends_on:
      database_api:
        condition: service_started
    ports:
      - "8000:8000"
    networks:
      - pg-network
    env_file:
      - .env
    volumes:
      - ./service_files:/app/service_files
      - ./models:/app/models


  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    depends_on:
      voice_to_text_api:
        condition: service_started
      redis:
        condition: service_started
    links:
      - voice_to_text_api
    ports:
      - "3000:3000"
    networks:
      - pg-network
    env_file:
      - .env
    environment:
      BOT_TOKEN: $BOT_TOKEN
    volumes:
      - ./service_files:/app/service_files


networks:
  pg-network:
    driver: bridge


volumes:
  redis_data: