db:
    type: "postgresql+asyncpg"
#    name: "test"
#    user: "admin"
#    password: "admin"
    host: "postgres"
    port: "5432"
    tables:
        users: "users"
        items: "items"
        interactions: "interactions"
        links: "links"
