db:
    type: "postgresql+asyncpg"
    host: "postgres"
    port: "5432"
    tables:
        users: "users"
        items: "items"
        interactions: "interactions"
        links: "links"
    data:
        dir_path: "./test_files"
        filenames:
            users: "test_users.csv"
            tasks: "test_tasks.csv"
