name: Deploy to PROD-VPS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ secrets.SERVICE_NAME }}
          docker build --network=host -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

  deploy:
    name: Deploy to Remote Server
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy on Remote Server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.SERVICE_NAME }}:latest
          docker stop ${{ secrets.SERVICE_NAME }} || true
          docker rm ${{ secrets.SERVICE_NAME }} || true
          docker image prune -f
          docker run --network=host --restart=always -d --name ${{ secrets.SERVICE_NAME }} ${{ secrets.DOCKER_USERNAME }}/${{ secrets.SERVICE_NAME }}:latest
